### ISSUE TITLE
Creating an event from an event template triggers a double event creation in zoom

### ISSUE THREAD

**Issue by richardsgf** [agileware/au.com.agileware.zoomzoom#3]
If you have...
* An event type that is associated with the zoomzoom civirules triggers
* An event template that has this event type

When you create a new event from that event type...
* The zoom fields are initially blank as expected.

When you hit the first Continue button...
* The CiviRules trigger and create an event on Zoom.
* *However* the zoom fields *are not* populated in the event. 

After editing other tabs on the event, if you return to the Info tab, you will find that the Zoom fields are blank.  At this point if you hit "Save" button on the Info tab, the CiviRules will trigger again, and a new event will be created in Zoom.  This time the fields on the event *will* be populated in the event.

The end result is
* You have two meetings or webinars in Zoom by the same name, but with different IDs
* One of these is orphaned
* Another one of these is correctly tied to an event in CiviCRM

To test this further, if you ...
* Do *not* use an event template
* Create an event normally and assign it an event type associated with zoom

then no double event is created in Zoom.  Only one event is created in Zoom and it is properly associated with the event in CiviCRM.

**Comment by agileware-justin** [comment]
Thanks for reporting @richardsgf 

We are currently working on a project with Event Templates and Zoom integration. So very relevant. We'll test this and if we can reproduce, push out a fix.

**Comment by agileware-iris** [comment]
Hi @richardsgf!

This turned out to be a much deeper issue then it first appears. The latest release includes code updates to prevent duplicate Zoom meetings being created. Please update to that version.

Additionally, please set all your Zoom fields to View Only to prevent CiviCRM overwriting the Zoom Details when copying from an Event Template. These are the fields in the Zoom field group.

![image](https://github.com/user-attachments/assets/581793d4-ed0d-4699-a720-4a8616fc6403)

What we observed was that the rule was running in the middle of CiviCRM copying an Event Template into a new event, so the updated Zoom fields were being overwritten by the Event Template's values. Setting the fields to View Only circumvents that override and correctly saves the Zoom Details.

Have a go and let us know if that fixes it for you.

**Comment by richardsgf** [comment]
Thank you so much for the super fast fix and the amazingly detailed description of what to do.  I'm sorry our upgrades move rather slow on our side but we have updated and all looks good so far.
Thank you so, so much!!
